### ISSUE TITLE
node.run_state['root_path'] conflicts with rbenv cookbook

### ISSUE THREAD

**Issue by petracvv** [sous-chefs/pyenv#68]
## :ghost: Brief Description

This is a companion issue to this rbenv issue: sous-chefs/ruby_rbenv#285

When using both the rbenv and pyenv cookbooks together and installing python and ruby versions for the same user, the resources from the 2nd cookbook do not work. This is because the same internal run_state attribute is used for tracking the root_path in both cookbooks.

## :pancakes: Cookbook version

3.2.0

## :woman_cook:  Chef-Infra Version

14.13.11

## :tophat: Platform details

RHEL7

## Steps To Reproduce

1. Write cookbook that creates a user and installs a ruby and python version for that user:
```ruby
     user 'jenkins' do
       manage_home true
     end

     rbenv_user_install 'jenkins'

     rbenv_ruby '2.7.1' do
       user 'jenkins'
     end

     pyenv_user_install 'jenkins'

     pyenv_python '3.8.2' do
       user 'jenkins'
     end
```
2. Run the recipe against a node in test-kitchen or a test env.
3. See the pyenv python installation fail

## :police_car: Expected behavior

I expect that both the ruby and python versions are installed with no error.

## :heavy_plus_sign: Additional context

I can work around the problem with a ruby block in between the pyenv and rbenv resources:

```ruby
ruby_block 'unset run_state' do
  block do
    node.run_state['root_path'] = {}
  end
end
```

**Comment by Xorima** [comment]
Hey,

Thanks for reporting this,

So this comes down to us doing things wrong in both cookbooks (We should be namespacing the run state to be something like: `node.run_state['sous-chefs']['cookbook_name']['root_path']`) 

Is this something you could alter on a PR for us, or would you rather I do it on both cookbooks?

Thanks

Jason

Relates to: https://github.com/sous-chefs/ruby_rbenv/issues/285
