### ISSUE TITLE
 `pyenv init -` no longer sets PATH.

### ISSUE THREAD

**Issue by manush1985** [sous-chefs/pyenv#83]
## :ghost: Brief Description

With the release of pyenv version 2.0.0 (https://github.com/pyenv/pyenv/releases/tag/v2.0.0) there are path issues when python is installed system wide via pyenv

## :pancakes: Cookbook version

3.4.1

## :woman_cook:  Chef-Infra Version

16

## :tophat: Platform details

Operating system: RHEL CentOS 7

## Steps To Reproduce

Just include the below three lines in your wrapper cookbook. After converge, whenever any user logs in, they get the error message: 
WARNING: `pyenv init -` no longer sets PATH.
Run `pyenv init` to see the necessary changes to make to your configuration.

Along with this message, it won't set the python path to the version provided.

```
pyenv_system_install 'system'
pyenv_python python_ver
pyenv_global python_ver
```

## :police_car: Expected behavior

The above warning should not appear.
default python version should be set to pyenv_global 'version#'

## :heavy_plus_sign: Additional context

-

**Comment by mromero-convoso** [comment]
Issue also occurs on Ubuntu 20.04 LTS.  I made a change to `/etc/profile.d/pyenv.sh` which corrected this behavior for me:

```
# Prefer a user pyenv over a system-wide install
if [ -s "${HOME}/.pyenv/bin" ]; then
    pyenv_root="${HOME}/.pyenv"
    pyenv_init="pyenv init -"
elif [ -s "/usr/local/pyenv" ]; then
    pyenv_root="/usr/local/pyenv"
    export PYENV_ROOT=${pyenv_root}
    # Rehashing will fail in a system install
    pyenv_init="pyenv init - --no-rehash"
fi

pyenv_init_path="${pyenv_root}/bin/pyenv init --path"

if [ -n "$pyenv_root" ]; then
    export PATH="${pyenv_root}/bin:$PATH"
    eval "$($pyenv_init_path)"
    eval "$($pyenv_init)"
fi
```

**Comment by mromero-convoso** [comment]
Turns out subsequent convergence runs will fail with the fix above as the "pyenv_system_install" resource wants to overwrite  the file.

**Comment by digorgonzola** [comment]
Yep. I also came across this problem on Ubuntu 20.04 with the system install. I got around it by creating a templated 'pyenv.sh' which get installed after the system install:

```
# Prefer a user pyenv over a system-wide install
if [ -s "${HOME}/.pyenv/bin" ]; then
    pyenv_root="${HOME}/.pyenv"
    pyenv_init="pyenv init -"
elif [ -s "<%= @pyenv_root %>" ]; then
    pyenv_root="<%= @pyenv_root %>"
    export PYENV_ROOT=${pyenv_root}
    # Rehashing will fail in a system install
    pyenv_init="pyenv init --path --no-rehash"
fi

if [ -n "$pyenv_root" ]; then
    export PATH="${pyenv_root}/bin:$PATH"
    eval "$($pyenv_init)"
fi
```

**Comment by manush1985** [comment]
yeah. templated pyenv.sh (or empty pyenv.sh) worked for me too.
